# Generated by Django 4.1.2 on 2022-11-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aName', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('Semester', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('SID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(blank=True, max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35, unique=True)),
                ('password', models.CharField(default='ChangeYourPassword', max_length=255, unique=True)),
                ('programme', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GsarsMain.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=35)),
                ('aID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GsarsMain.activityrecord')),
                ('sID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GsarsMain.students')),
            ],
        ),
        migrations.CreateModel(
            name='Focal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=35)),
                ('role', models.CharField(max_length=35)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GsarsMain.admin')),
            ],
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='fID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GsarsMain.focal'),
        ),
    ]
