# Generated by Django 4.1.2 on 2022-11-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GsarsMain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focal',
            name='adminID',
        ),
        migrations.RemoveField(
            model_name='record',
            name='aID',
        ),
        migrations.RemoveField(
            model_name='record',
            name='sID',
        ),
        migrations.RemoveField(
            model_name='students',
            name='adminID',
        ),
        migrations.DeleteModel(
            name='ActivityRecord',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Focal',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
