# Generated by Django 4.1.2 on 2022-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GsarsMain', '0004_alter_students_email_alter_students_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sl',
            field=models.IntegerField(default=1),
        ),
    ]
