# Generated by Django 4.1.2 on 2022-11-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GsarsMain', '0005_students_sl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
