# Generated by Django 4.1.2 on 2022-11-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GsarsMain', '0006_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('SID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(blank=True, max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35)),
                ('password', models.CharField(default='ChangeYourPassword', max_length=255)),
                ('programme', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=50)),
                ('sl', models.IntegerField(default=1)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
